// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InsuranceQuoteTestsTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void getInsuranceQuote_AllValidInputs_Age25_Exp03_Acc04_NoInsurance()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(792, 864);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aryamaan");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Kothakonda");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("342 Mill Street");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N2M 0A4");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-781-2925");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("aryamaankothakonda@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$2500"));
        }
    }
    [Test]
    public void getInsuranceQuote_AllValidInputs_Age25_Exp03_Acc04_Insurance2500()
    {
        driver.Navigate().GoToUrl("http://localhost/");
        driver.Manage().Window.Size = new System.Drawing.Size(792, 864);
        driver.FindElement(By.LinkText("prog8170a04/")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aryamaan");
        driver.FindElement(By.Id("lastName")).SendKeys("Kothakonda");
        driver.FindElement(By.Id("address")).SendKeys("342 Mill Street");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2M 0A4");
        driver.FindElement(By.Id("phone")).SendKeys("5197812925");
        driver.FindElement(By.Id("email")).SendKeys("aryamaankothakonda@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-781-2925");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("4");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
    [Test]
    public void getInsuranceQuote_AllValidInputs_Age35_Exp10_Acc02_Insurance1350()
    {
        driver.Navigate().GoToUrl("http://localhost/");
        driver.Manage().Window.Size = new System.Drawing.Size(792, 864);
        driver.FindElement(By.LinkText("prog8170a04/")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aryamaan");
        driver.FindElement(By.Id("lastName")).SendKeys("Kothakonda");
        driver.FindElement(By.Id("address")).SendKeys("342 Mill Street");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2M 0A4");
        driver.FindElement(By.Id("phone")).SendKeys("5197812925");
        driver.FindElement(By.Id("email")).SendKeys("aryamaankothakonda@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-781-2925");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("10");
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$1350"));
        }
    }
    [Test]
    public void getInsuranceQuote_InvalidAge_Exp03_Acc00_ValidationError()
    {
        driver.Navigate().GoToUrl("http://localhost/");
        driver.Manage().Window.Size = new System.Drawing.Size(792, 864);
        driver.FindElement(By.LinkText("prog8170a04/")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aryamaan");
        driver.FindElement(By.Id("lastName")).SendKeys("Kothakonda");
        driver.FindElement(By.Id("address")).SendKeys("342 Mill Street");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2M 0A4");
        driver.FindElement(By.Id("phone")).SendKeys("5197812925");
        driver.FindElement(By.Id("email")).SendKeys("aryamaankothakonda@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-781-2925");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("-1");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Please enter a value greater than or equal to 16."));
    }
    [Test]
    public void getInsuranceQuote_InvalidEmail_Age28_Exp03_Acc00_ValidationError()
    {
        driver.Navigate().GoToUrl("http://localhost/");
        driver.Manage().Window.Size = new System.Drawing.Size(792, 864);
        driver.FindElement(By.LinkText("prog8170a04/")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aryamaan");
        driver.FindElement(By.Id("lastName")).SendKeys("Kothakonda");
        driver.FindElement(By.Id("address")).SendKeys("342 Mill Street");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2M 0A4");
        driver.FindElement(By.Id("phone")).SendKeys("5197812925");
        driver.FindElement(By.Id("email")).SendKeys("aryamaankothakonda@gmail.com");
        {
            var element = driver.FindElement(By.Id("email"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
        }
        {
            var element = driver.FindElement(By.Id("email"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.Id("email"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
        }
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("aryamaankothakonda");
        driver.FindElement(By.CssSelector(".card:nth-child(1) > div:nth-child(2)")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-781-2925");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("28");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
    }
    [Test]
    public void getInsuranceQuote_InvalidPhoneNo_Age27_Exp03_Acc00_ValidationError()
    {
        driver.Navigate().GoToUrl("http://localhost/");
        driver.Manage().Window.Size = new System.Drawing.Size(792, 864);
        driver.FindElement(By.LinkText("prog8170a04/")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aryamaan");
        driver.FindElement(By.Id("lastName")).SendKeys("Kothakonda");
        driver.FindElement(By.Id("address")).SendKeys("342 Mill Street");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2M 0A4");
        driver.FindElement(By.Id("phone")).SendKeys("5197812925");
        driver.FindElement(By.Id("email")).SendKeys("aryamaankothakonda@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("5197");
        driver.FindElement(By.CssSelector("#addForm > .form-group")).Click();
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("27");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
    }
    [Test]
    public void getInsuranceQuote_InvalidPostalCode_Age35_Exp17_Acc01_ValidationError()
    {
        driver.Navigate().GoToUrl("http://localhost/");
        driver.Manage().Window.Size = new System.Drawing.Size(792, 864);
        driver.FindElement(By.LinkText("prog8170a04/")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aryamaan");
        driver.FindElement(By.Id("lastName")).SendKeys("Kothakonda");
        driver.FindElement(By.Id("address")).SendKeys("342 Mill Street");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2M 0A4");
        driver.FindElement(By.Id("phone")).SendKeys("5197812925");
        driver.FindElement(By.Id("email")).SendKeys("aryamaankothakonda@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-781-2925");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N2M");
        driver.FindElement(By.CssSelector("#addForm > .form-group")).Click();
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("17");
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
    }
    [Test]
    public void getInsuranceQuote_NoDrivingExp_Age27_Exp00_Acc00_ValidationError()
    {
        driver.Navigate().GoToUrl("http://localhost/");
        driver.Manage().Window.Size = new System.Drawing.Size(792, 864);
        driver.FindElement(By.LinkText("prog8170a04/")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aryamaan");
        driver.FindElement(By.Id("lastName")).SendKeys("Kothakonda");
        driver.FindElement(By.Id("address")).SendKeys("342 Mill Street");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2M 0A4");
        driver.FindElement(By.Id("phone")).SendKeys("5197812925");
        driver.FindElement(By.Id("email")).SendKeys("aryamaankothakonda@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-781-2925");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("27");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("0");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.CssSelector(".card-body")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$4000"));
        }
    }
    [Test]
    public void getInsuranceQuote_OmitAccidents_Age37_Exp08_ValidationError()
    {
        driver.Navigate().GoToUrl("http://localhost/");
        driver.Manage().Window.Size = new System.Drawing.Size(792, 864);
        driver.FindElement(By.LinkText("prog8170a04/")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aryamaan");
        driver.FindElement(By.Id("lastName")).SendKeys("Kothakonda");
        driver.FindElement(By.Id("address")).SendKeys("342 Mill Street");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2M 0A4");
        driver.FindElement(By.Id("phone")).SendKeys("5197812925");
        driver.FindElement(By.Id("email")).SendKeys("aryamaankothakonda@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-781-2925");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("37");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("8");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
    }
    [Test]
    public void getInsuranceQuote_OmitAge_Exp05_Acc00_ValidationError()
    {
        driver.Navigate().GoToUrl("http://localhost/");
        driver.Manage().Window.Size = new System.Drawing.Size(792, 864);
        driver.FindElement(By.LinkText("prog8170a04/")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aryamaan");
        driver.FindElement(By.Id("lastName")).SendKeys("Kothakonda");
        driver.FindElement(By.Id("address")).SendKeys("342 Mill Street");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2M 0A4");
        driver.FindElement(By.Id("phone")).SendKeys("5197812925");
        driver.FindElement(By.Id("email")).SendKeys("aryamaankothakonda@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-781-2925");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.CssSelector(".container")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
    }
    [Test]
    public void getInsuranceQuote_OmitDrivingExp_Age45_Acc00_ValidationError()
    {
        driver.Navigate().GoToUrl("http://localhost/");
        driver.Manage().Window.Size = new System.Drawing.Size(792, 864);
        driver.FindElement(By.LinkText("prog8170a04/")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aryamaan");
        driver.FindElement(By.Id("lastName")).SendKeys("Kothakonda");
        driver.FindElement(By.Id("address")).SendKeys("342 Mill Street");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2M 0A4");
        driver.FindElement(By.Id("phone")).SendKeys("5197812925");
        driver.FindElement(By.Id("email")).SendKeys("aryamaankothakonda@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-781-2925");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("45");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
    }
}
